Add GUAC contribution application
ossf/tac pull request #178
Opened 2023-06-20 20:36 UTC by mlieberman85

Application for GUAC to be adopted.

2023-07-10 11:50 UTC, lehors requested changes
Looks good overall. Just need to update the IP section once it's completed.

2023-07-10 11:50 UTC, lehors commented on process/project-lifecycle-documents/guac_sandbox.md
> +I will include quotes from adopters:
```suggestion
Here are quotes from adopters: 
```

2023-07-10 11:50 UTC, lehors commented on process/project-lifecycle-documents/guac_sandbox.md
> +  * TAC docs make this process unclear. We will work with LF on any due diligence, just point us in the right direction.
This section needs to be updated.

2023-09-28 10:52 UTC, lehors approved these changes

2023-10-03 01:10 UTC, lumjjb commented
Remove /hold

2023-10-06 16:18 UTC, SecurityCRob approved these changes

2023-10-06 17:40 UTC, steiza approved these changes

2023-10-10 13:57 UTC, bobcallaway approved these changes

2023-10-10 13:58 UTC, torgo approved these changes
lgtm (looks guac to me)

2023-10-10 14:01 UTC, di approved these changes

2023-10-10 15:24 UTC, merged