Update tac-and-scir-election-process.md
ossf/tac pull request #223
Opened 2023-11-17 17:47 UTC by SecurityCRob

2023-11-21 07:40 UTC, lehors requested changes

2023-11-21 07:40 UTC, lehors commented on elections/tac-and-scir-election-process.md
> +The OpenSSF Technical Advisory Council (TAC) is composed of nine total individuals, six of whom are elected from the community, three of which are appointed by the Governing Board.  TAC seats are for
```suggestion
The OpenSSF Technical Advisory Council (TAC) is composed of nine total individuals, six of whom are elected by the community, three of which are appointed by the Governing Board.  TAC seats are for 2 year terms, 50% of which are open for community vote every year.  The Governing Board-appointed seats are for a one-year term.
```

2023-11-21 14:03 UTC, lehors approved these changes
Fixed the typo for you. All good now. :-)

2023-11-22 14:20 UTC, steiza approved these changes

2023-11-24 16:40 UTC, merged