Add slack and github issues links
ossf/tac pull request #27
Opened 2020-10-01 19:25 UTC by dcmiddle

Addresses _issues_ portion of https://github.com/ossf/tac/issues/14
and adds slack.

The `Get Involved` section heading comes from the proposed template https://github.com/ossf/project-template/pull/1

2020-10-01 20:24 UTC, mayakacz approved these changes

2020-10-02 13:06 UTC, christo4ferris approved these changes
LGTM

2020-10-02 13:11 UTC, christo4ferris requested changes
actually, checking the slack link and it appears it has expired. Will need to update with a valid invite link

2020-10-02 13:28 UTC, LindsayLF commented
Hi @christo4ferris - Here is a new invite link for slack: https://join.slack.com/t/openssf/shared_invite/zt-hxttbilt-R4bR7Gcp0eY2E8zZZZD65w 
(They expire approx every 30 days)

2020-10-02 15:29 UTC, dcmiddle commented
Updated with a fresh link. As Lindsay mentions it looks like these expire after a month. We'll want to come up with a more permanent way to link this. From a brief search it seems one needs to setup some ad-hoc mechanism to workaround slack's limitation. To make sure we can ramp people into our community during this initial phase, though, I think it still makes sense to post the ephemeral link and not wait for creating new infrastructure.

2020-10-05 13:12 UTC, merged