docs: add zarf as an openssf sandbox project
ossf/tac pull request #341
Opened 2024-06-05 16:35 UTC by salaxander

2024-06-05 16:40 UTC, lehors commented
As documented in the [Project creation or change of lifecycle stage](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#project-creation-or-change-of-lifecycle-stage) this PR should also modify the table listing the projects in the README of this repo. In this case it should add the project with the status as Sandbox, with a link to the change request md file that you are adding as part of this PR.
Thank you.

2024-06-05 16:41 UTC, hythloda commented
We have requested the IP / License for this project intake

2024-06-05 16:46 UTC, salaxander commented
> As documented in the [Project creation or change of lifecycle stage](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#project-creation-or-change-of-lifecycle-stage) this PR should also modify the table listing the projects in the README of this repo. In this case it should add the project with the status as Sandbox, with a link to the change request md file that you are adding as part of this PR. Thank you.

Note: I've added Zarf to the table in the README. We will be moving the project to a company independent GitHub org in the near future. At that time I'll be sure to update this link.

2024-06-05 17:33 UTC, SecurityCRob commented
@hepwori has this been discussed and approved by the SCI WG?

2024-06-05 17:59 UTC, lehors commented on README.md
> +| Zarf          | https://github.com/defenseunicorns/zarf | [Meeting Notes](https://docs.google.com/document/d/1Ww5XOICluxIY_bAsyVieLe9GU9FpXJ3LwSCZxqOSLaM/edit#heading=h.wq25h5ks8vsu) | Supply Chain
```suggestion
| Zarf          | https://github.com/defenseunicorns/zarf | [Meeting Notes](https://docs.google.com/document/d/1Ww5XOICluxIY_bAsyVieLe9GU9FpXJ3LwSCZxqOSLaM/edit#heading=h.wq25h5ks8vsu) | Supply Chain Integrity WG   | [Sandbox](process/project-lifecycle-documents/zarf_sandbox_stage.md)       |
```

2024-06-05 18:01 UTC, lehors commented
> We will be moving the project to a company independent GitHub org in the near future. At that time I'll be sure to update this link.

Since you have to move it you might want to consider simply moving it under ossf.

2024-06-05 18:30 UTC, hepwori commented
> @hepwori has this been discussed and approved by the SCI WG?

Preliminarily, yes! We've had two live briefings over the last few months, and in the WG meeting earlier today we had a show of hands as to adding Zarf with no objections. The final approval step will be to inform the mailing list; I hope to send that out today, referencing the link to this issue.

2024-06-06 01:14 UTC, CoS-Harry commented
Bennett will work with the maintainers of Zarf following TAC action on the application to move it to the right org.

2024-06-07 18:07 UTC, steiza commented
Does this require a TAC vote? Or once @hepwori says it's accepted are we good to go (modulo any missing information on the pull request?)

From https://github.com/ossf/tac/blob/main/process/project-lifecycle.md:

> Projects must seek one TAC sponsor or one WG sponsor (if reporting to a WG)
> - TAC or WG sponsor agrees to attend Project meetings regularly
> - TAC or WG sponsor does not need to have a formal role in Project, e.g., maintainer
> - TAC or WG sponsor requests TAC approval

If the project is reporting to SCI WG, and @hepwori is the WG sponsor and says it's good, I think we're good to go? It is possible I misunderstand the process!

2024-06-07 19:09 UTC, hythloda commented
Before merging we need to review the IP and license review.

Before any announcement the charter needs approval by zarf and the contribution agreement needs signed.

2024-06-08 02:49 UTC, sevansdell commented
I approve pending IP and license review. the charter approval by zarf and the contribution agreement signed, the SCI WG approval, and the TAC sponsor is identified. (I will be out the June 11 TAC meeting, and am trying to be proactive).

2024-06-10 16:01 UTC, marcelamelara approved these changes
I approve, pending the IP and license review.

2024-06-11 12:48 UTC, SecurityCRob approved these changes
Isaac and SCI have agreed on including zarf into their WG.

2024-06-11 16:16 UTC, hythloda commented
The IP and License Review is expected by June 21st. Sorry for the delay.

2024-06-12 12:38 UTC, lehors requested changes
I support the proposal but request the answer about the IP and licensing due diligence be modified once the due diligence is completed. (The request for change will also prevent premature merge of this PR.)

2024-06-12 12:38 UTC, lehors commented on process/project-lifecycle-documents/zarf_sandbox_stage.md
> +  * Not applicable - There has been no formal trademark filed by Defense Unicorns.
I don't believe this is the correct answer. The requirement applies to all projects coming from outside OpenSSF.
I suggest this be changed once the due diligence is complete.

2024-06-17 17:04 UTC, salaxander commented
@hythloda everything going ok with the license review? Definitely let us know if there's anything we can do to help move things along :) 

Thanks!

2024-06-17 17:17 UTC, hythloda commented
> @hythloda everything going ok with the license review? Definitely let us know if there's anything we can do to help move things along :)
> 
> Thanks!

Thanks @salaxander ! The review just takes some internal time. Hoping it gets done soon this week rather than later :)

2024-06-20 06:51 UTC, jeffcshapiro commented
LF License Intake Scan Report:

LICENSE INTAKE SCAN & ANALYSIS:  OpenSSF:  Zarf
DISTRIBUTION:  Amanda Martin, https://github.com/ossf/tac/pull/341

- This intake scan is a static analysis of the source code in your repository.  A dependency scan was not performed.  Once a project is added to LFX [https://security.lfx.linuxfoundation.org], you can use SNYK to view a dependency scan for both licenses and vulnerabilities.

CODE SCANNED:  [pulled 19–JUNE-2024]
https://github.com/defenseunicorns/zarf

PROJECT LICENSE: Apache-2.0
- Top level project license file found in repo

SPDX LICENSE IDENTIFIERS:  SPDX license identifiers were found in source file headers.

PERMISSIVE LICENSES:  Apache-2.0

COPYLEFT LICENSES:  None found

SOURCE AVAILABLE LICENSES:  None found

PROPRIETARY LICENSES:  None found

LICENSE CONFLICTS: None found

BINARY / PACKAGE FILES:  None found

THIRD PARTY CODE / DEPENDENCIES:  None found

THIRD PARTY NOTICE FILE:  None found

SUMMARY FINDINGS:  All of the scanned code is under the project license, Apache-2.0.  SPDX license identifiers were found in source file headers.  No license conflicts found.  No dependencies or third party code detected in repo.

2024-06-20 15:06 UTC, salaxander commented
@lehors updated now that the license scan is complete

2024-06-20 16:47 UTC, lehors approved these changes
All clear. Welcome to OpenSSF!

2024-06-20 16:47 UTC, merged