Create security_baseline_sandbox_stage.md
ossf/tac pull request #354
Opened 2024-07-11 18:42 UTC by Danajoyluck

2024-07-11 20:44 UTC, sevansdell requested changes
I think this is coming along well. There are three places I didn't see information before I'm comfortable approving.

1. In the goal section, can you describe a bit more about what the SIG will do to evolve the baseline to prepare for LF wide adoption? (e.g. work with graduated projects to proof of concept the baseline and get feedback). What does "good" look like to know you're done and ready to apply to rest of LF?
2. in the governance section, please clarify the initial governance request (if I remember correctly from the TAC meeting your request is to initially fall under TAC governance.
3.  URLS. I believe there was some conversation about if the initial repo should be in the TAC, or a separate repo while evaluating the baseline for OpenSSF. In some comments I understood this might evolve when it applies to the rest of the LF. Need to decide and populate initial URLs.

Thanks!

2024-07-12 19:04 UTC, Danajoyluck commented
> I think this is coming along well. There are three places I didn't see information before I'm comfortable approving.
> 
> 1. In the goal section, can you describe a bit more about what the SIG will do to evolve the baseline to prepare for LF wide adoption? (e.g. work with graduated projects to proof of concept the baseline and get feedback). What does "good" look like to know you're done and ready to apply to rest of LF?
> 2. in the governance section, please clarify the initial governance request (if I remember correctly from the TAC meeting your request is to initially fall under TAC governance.
> 3. URLS. I believe there was some conversation about if the initial repo should be in the TAC, or a separate repo while evaluating the baseline for OpenSSF. In some comments I understood this might evolve when it applies to the rest of the LF. Need to decide and populate initial URLs.
> 
> Thanks!

Thanks a lot @sevansdell I updated the document to address question 1 and 2. I assumed 3 is comment. Once the SIG is formed, we will have a repo,  the URIs and document update process  will be sorted out with TAC

2024-07-13 11:28 UTC, lehors commented on process/sig-lifecycle-documents/security_baseline_sandbox_stage.md
> +CRob and Dana Wang had conversations about this inititve. CRob has agreed to be the sponsor of this SIG and welcome the group to join Security Best Practices Working Group.
```suggestion
CRob and Dana Wang had conversations about this initiative. CRob has agreed to be the sponsor of this SIG and welcome the group to join Security Best Practices Working Group. 
```

2024-07-17 05:18 UTC, marcelamelara approved these changes
Thanks @Danajoyluck ! This looks good to me!

2024-07-18 17:04 UTC, SecurityCRob approved these changes
The BEST WG voted to adopt Baseline as a SIG

2024-07-23 14:04 UTC, mlieberman85 approved these changes
lgtm

2024-07-23 14:40 UTC, sevansdell approved these changes
Thanks for reviewed changes.

2024-07-23 14:49 UTC, camaleon2016 approved these changes

2024-07-23 15:02 UTC, steiza approved these changes

2024-07-23 15:06 UTC, torgo approved these changes
lgtm 👍🏻

2024-07-23 15:43 UTC, marcelamelara approved these changes
Not sure why my original approval was removed, but I still approve this!

2024-07-23 16:06 UTC, merged