Apply to donate vuln-reach to the OpenSSF
ossf/tac pull request #388
Opened 2024-09-26 16:34 UTC by louislang

2024-09-30 14:59 UTC, SecurityCRob commented
Has the group been speaking with our Security Tooling WG, and that group endorses this motion?  We'll want to see evidence of public meetings and minutes as the project would move over to the foundation.

2024-09-30 20:43 UTC, steiza reviewed
Thanks for making this pull request! In this pull request can you also add `vuln-reach` to the Projects table on https://github.com/ossf/tac/blob/main/README.md#projects?

Is development of this project primarily happening on https://github.com/phylum-dev/vuln-reach in the `main` branch, or elsewhere? There doesn't seem to be a lot of recent activity.

To be clear, recent activity isn't a requirement for becoming a sandbox project, but sometimes people think "oh, I'll donate this to the OpenSSF, and they'll figure out how to get contributors!" and I just want to make sure we're on the same page - projects are responsible for figuring out how to get community participation.

2024-10-01 02:04 UTC, mlieberman85 commented
Craig is listed as a maintainer but according to GitHub he has never contributed to the project. Can you go into more detail what he's a maintainer of?

Beyond that I do think this project is good for openssf.

2024-10-01 16:03 UTC, louislang commented
> Thanks for making this pull request! In this pull request can you also add `vuln-reach` to the Projects table on https://github.com/ossf/tac/blob/main/README.md#projects?

Yes, of course.

> Is development of this project primarily happening on https://github.com/phylum-dev/vuln-reach in the `main` branch, or elsewhere? There doesn't seem to be a lot of recent activity.

We began this work some time ago as part of our proprietary product. We got it to a steady state for Javascript/Typescript, before shifting our core product focus a bit. We recently decided to open source this.

> Craig is listed as a maintainer but according to GitHub he has never contributed to the project. Can you go into more detail what he's a maintainer of?

I wasn't personally involved with the initial presentation to the WG, so I'm just going with what was passed along to me. As I understand it, Craig was interested in supporting the project. I will follow up with our team to get a better understanding on this specifically.

2024-10-08 15:34 UTC, ware commented
> I wasn't personally involved with the initial presentation to the WG, so I'm just going with what was passed along to me. As I understand it, Craig was interested in supporting the project. I will follow up with our team to get a better understanding on this specifically.

I think there are two things being conflated here.  Let's break them up.

1. @craigmcl volunteered to be the ST:WG sponsor.  There were some further discussions that were supposed to take place between Craig and Aaron Bray but don't know if they took place.  If Craig is unable to be that sponsor, I will go ahead and be the sponsor so I don't think this is a hangup.
2. I don't know that Craig has signed up to be a maintainer but invite him to clarify.  I'm not sure it meets the spirit of the [Sandbox Entry Requirements](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#sandbox-entry-requirements-and-considerations) to list someone as a maintainer that has not made any contributions though I invite TAC comment.

2024-10-10 12:55 UTC, SecurityCRob commented
> > I wasn't personally involved with the initial presentation to the WG, so I'm just going with what was passed along to me. As I understand it, Craig was interested in supporting the project. I will follow up with our team to get a better understanding on this specifically.
> 
> I think there are two things being conflated here. Let's break them up.
> 
> 1. @craigmcl volunteered to be the ST:WG sponsor.  There were some further discussions that were supposed to take place between Craig and Aaron Bray but don't know if they took place.  If Craig is unable to be that sponsor, I will go ahead and be the sponsor so I don't think this is a hangup.
> 2. I don't know that Craig has signed up to be a maintainer but invite him to clarify.  I'm not sure it meets the spirit of the [Sandbox Entry Requirements](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#sandbox-entry-requirements-and-considerations) to list someone as a maintainer that has not made any contributions though I invite TAC comment.

Thanks Ryan.  Re: #2 correct.  We want to ensure that as projects develop and grow that they have a thriving community around to support them (hence the desire to house them within a like-minded/focused working group).  Having multiple maintainers is critical to the long-term viability of a project as it allows for things like code reviewing, dual-control, etc., and helps share the ongoing burden that maintenance and community engagement.  We also prefer those maintainers to be from different organizations to help weather any challenges that could arise from organizational changes that impact the maintainer (that in fact is a requirement at higher levels within the TI lifecycle).

2024-10-15 22:49 UTC, sevansdell requested changes
Please identify additional maintainers based on comments about engagement from Craig at Stacklock. Are there any blockers the TAC can provide in helping you navigate this?

2024-10-22 22:58 UTC, marcelamelara commented
+1 To needing to address the diverse maintainership requirement.

@louislang Some ideas to potentially engage some more folks from the community: 1) put out a call for contributors in the OpenSSF Slack channels (`#general`,`#wg-security-tooling` and `#wg-dei` might be good options), 2) give an updated presentation at the ST:WG or other WGs for the added visibility.

2024-12-06 17:02 UTC, sevansdell requested changes
Please work with Ryan Ware to identify a TAC sponsor. I am comfortable with this being a sandbox stage project with active engagement from a TAC member and the Security Tooling WG. I would also like the TAC sponsor/Security Tooling WG lead/vuln reach maintainers to discuss a timeline to progress to incubating stage, and after that time expires, if there is no activity, to archive the project. This is an arbitrary deadline however, and if the team is actively working on the project making progress towards sandbox, the deadline can certainly be discussed with the TAC sponsor/Security Tooling WG lead to extend to another milestone date.

2025-01-09 16:47 UTC, marcelamelara commented
@ware @louislang Is this application still in progress? If yes, it'd be great to get an update. Otherwise, I suggest we close this PR and revisit this when the we're ready to reopen the application. 

CC @ossf/tac

2025-01-24 22:06 UTC, marcelamelara commented
I was revisiting this application, and seeing that there hasn't been a lot of active development [since late 2023](https://github.com/phylum-dev/vuln-reach/commits/main/) in the vuln-reach repo, I do worry that this project doesn't currently have the level of activity/interest needed for a sandbox project.

2025-08-20 17:48 UTC, marcelamelara commented
@GeauxJD any updates on this? If not, we can close this.

2025-09-01 18:29 UTC, ware commented
> @GeauxJD any updates on this? If not, we can close this.

@marcelamelara, is there a process for closing donation requests such as this when they haven't been pursued to completion?  It looks like we are rapidly coming to the point where this has been open for a year and there has been many months without response from the project being donated.

2025-09-02 17:56 UTC, marcelamelara commented
> is there a process for closing donation requests such as this when they haven't been pursued to completion?

In the past, I believe we've simply closed the issue/PR, but I don't think there's anything more formal beyond that. 

@ossf/tac any thoughts?

2025-09-02 17:58 UTC, bobcallaway commented
i'd just close it; easy enough to re-open it if something changes.

2025-09-02 19:20 UTC, closed without merging