Create 2024-Q4-VULN-WG.md
ossf/tac pull request #407
Opened 2024-11-05 17:17 UTC by SecurityCRob

draft pr for vuln wg update

2024-11-07 15:28 UTC, mlieberman85 approved these changes
LGTM

2024-11-07 21:47 UTC, andrewpollock commented on TI-reports/2024/TI-reports/2024/2024-Q4-VULN-WG.md
> +- Coordinatd Vulnerability Disclosure (CVD) Guides [link](https://github.com/ossf/oss-vulnerability-guide)
Fix spelling mistake

```suggestion
- Coordinated Vulnerability Disclosure (CVD) Guides [link](https://github.com/ossf/oss-vulnerability-guide)
```

2024-11-07 21:47 UTC, andrewpollock commented on TI-reports/2024/TI-reports/2024/2024-Q4-VULN-WG.md
> +- OSV - Adrew Pollock (Google)
Not me 😁

```suggestion
- OSV - Oliver Chang (Google)
```

2024-11-07 21:47 UTC, andrewpollock commented on TI-reports/2024/TI-reports/2024/2024-Q4-VULN-WG.md
> +- Best practices guides forcused on assorted OSS personas explaining how to have more effective coorindated vulnerability disclosure processes.
Fix spelling mistakes

```suggestion
- Best practices guides focused on assorted OSS personas explaining how to have more effective coordinated vulnerability disclosure processes.
```

2024-11-07 21:47 UTC, andrewpollock commented on TI-reports/2024/TI-reports/2024/2024-Q4-VULN-WG.md
> +#### Current Status
How should this be expressed?
/cc @oliverchang

2024-11-07 21:58 UTC, taladrane approved these changes

2024-11-07 21:58 UTC, taladrane commented on TI-reports/2024/TI-reports/2024/2024-Q4-VULN-WG.md
> +- Open Source Vulnerability (OSV) schema) [link](https://github.com/ossf/osv-schema)
```suggestion
- Open Source Vulnerability (OSV) schema [link](https://github.com/ossf/osv-schema)
```

2024-11-17 19:12 UTC, steiza reviewed
Minor: the path of the file is weird, it looks like it includes `TI-reports/2024` twice?

2024-11-21 00:57 UTC, marcelamelara commented
Is this PR ready to be reviewed? I see the DRAFT label, but the PR is marked as ready. Thanks!

2024-12-03 18:44 UTC, marcelamelara requested changes
Aside from the TTX exercise, the sparse current status updates and empty "Up Next" sections give the impression that the SIGs aren't particularly active at the moment. Are they on hiatus or are there other concerns that need the TAC's attention?

2024-12-04 20:18 UTC, steiza approved these changes
I share @marcelamelara's concerns about the sparse updates, but I think that with the time that has passed, this is all we're going to get for now.

Separately, there's an upcoming working group leads meeting where we'll asking folks to start thinking about 2025 plans.

2024-12-04 20:19 UTC, steiza requested changes
Oops! I didn't realize we hadn't fixed the path of the file yet. Can we change it from `TI-reports/2024/TI-reports/2024/2024-Q4-VULN-WG.md` to `TI-reports/2024/2024-Q4-VULN-WG.md` please?

2024-12-16 22:26 UTC, marcelamelara approved these changes
In the interest of moving this along, I'm going to accept this, but I do hope for a more detailed update in Q1 of 2025, especially around WG health and community engagement.

2025-01-21 15:39 UTC, steiza approved these changes

2025-01-21 15:40 UTC, merged